name: Build and Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor project
        run: dotnet publish -c Release -o publish

      - name: Change base href in index.html
        run: sed -i 's|<base href="/" />|<base href="/harveerportfolio/" />|' publish/wwwroot/index.html

      - name: Copy index.html to 404.html for SPA routing
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish/wwwroot
